[package]
name = "iso_currency"
description = "ISO 4217 currency codes"
version = "0.2.0"
authors = ["Rostislav Raykov <z@zbrox.org>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/zbrox/iso_currency"
documentation = "https://docs.rs/iso_currency/0.1.0/"
homepage = "https://github.com/zbrox/iso_currency"
readme = "README.md"

[dependencies]
serde = { version = "1.0.107", optional = true, features = ["derive"] }
